FROM python:3.11-slim

WORKDIR /app

COPY Requirments_fastapi.txt .

RUN pip install --no-cache-dir -r Requirments_fastapi.txt

COPY . .

RUN ls -R /app/Stds || echo "No PDFs found"

EXPOSE 8000

CMD ["uvicorn","Fastapi:app","--host","0.0.0.0","port", "8000"]